User/squidman/2022/03/19/add the new sprites patches to the client UI
squid-man/MegaMan2Randomizer2 pull request #92
Opened 2022-03-28 06:50 UTC by squid-man

1. Adding character sprites, random enemy sprites, random boss sprites, random special weapon sprites.
2. Dramatically decreasing the chance that the Wily Machine is weak to buster.
3. Adding custom ASM routine to enable item spawns in Wily 5.
4. Adding respawning large weapon energy to Wily 5.

2022-03-28 08:19 UTC, dagit requested changes
I think it would be good to separate out the purely new UI/sprite changes from the randomization changes (wily5 vulnerability chance and refills). As in, separate PRs.

The CI also needs to be updated when you bump the dotnet version.

I don't know that the individual readme files have much value. It might be better to just have one sprite readme with credits? Not something I feel strongly about.

2022-03-28 08:19 UTC, dagit commented on MM2RandoLib/MM2RandoLib.csproj
> +        <TargetFramework>net6.0</TargetFramework>
You'll also need to change this in `.github/ci.yml` and `.github/release-builds.yml` (should be pretty obvious which lines to change). Right now all the CI stuff is failing on this PR because they're set to use a dotnet 5 install.

2022-03-28 08:19 UTC, dagit commented on MM2RandoLib/Patcher/Patch.cs
> +                // Throw an error?
I think this (and the other "Throw an error?" comment) need to be addressed before we merge this. While these errors should be exceedingly rare, I think we should definitely be letting the user know. Given that it shouldn't really ever happen, I think something super simple like just throwing an exception that gets displayed in a message box is plenty good.

2022-03-28 08:19 UTC, dagit commented on MM2RandoLib/Randomizers/RItemGet.cs
> +                    _ => "",
This is minor because it's just for the spoiler log, but I don't like this style because if we ever come through and add more items you won't get a compile error here, but you also won't see "Item 4". If you match on all the cases then adding or removing values in the enum will cause this site to get flagged by a compiler error and you can update it.

2022-03-28 08:19 UTC, dagit commented on MM2RandoLib/Randomizers/RWeaknesses.cs
> +                if (rBuster > 0.95)
Was this discussed somewhere? Also, it seems like a weird change to include with a PR that is ostensibly just UI changes.

2022-03-28 08:19 UTC, dagit commented on MM2RandoLib/Resources/SpritePatches/WeaponSpriteRandomizer.cs
> +        public static void ApplySprites(ISeed in_Seed, Patch in_Patch, String in_TargetFileName)
It seems like these `FooSpriteRandomizer` files have the same interface? Could we refactor `ApplySprites` for example, to be in a base class. Then each of these classes would just list all the arrays and override some instance variable of the base class for the list of lists (`FOO_SPRITE_COLLECTION`).

2022-03-28 08:19 UTC, dagit commented on MM2RandoLib/Utilities/MiscHacks.cs
> +        public static void AddWily5SubroutineWithItemSpawns(Patch p)
Similar to the other randomization changes, I'm not sure these make sense in the context of the current PR. They feel like they should be in a separate PR.

2022-03-29 21:08 UTC, squid-man commented
Superseded by https://github.com/squid-man/MegaMan2Randomizer2/pull/93

2022-03-29 21:08 UTC, closed without merging